const fs = require('fs');
const path = require('path');
const s3Client = require('../config/s3');
const { Upload } = require('@aws-sdk/lib-storage');
const { v4: uuidv4 } = require('uuid');

exports.uploadFile = async (file) => {
  const useS3 = process.env.USE_S3 === 'true';

  let file_url = '';
  let file_type = file.mimetype.split('/')[1]; // e.g. 'jpeg', 'png'
  if (file_type === 'jpeg') file_type = 'jpg';
  const file_size = file.size;

  if (useS3 && s3Client) {
    // Read the locally saved file to upload to S3, then delete it locally
    const fileStream = fs.createReadStream(file.path);
    const key = `content/${uuidv4()}${path.extname(file.originalname)}`;
    
    const uploader = new Upload({
      client: s3Client,
      params: {
        Bucket: process.env.AWS_S3_BUCKET,
        Key: key,
        Body: fileStream,
        ContentType: file.mimetype,
        // ACL: 'public-read' // Only if bucket allows ACLs
      },
    });

    await uploader.done();
    file_url = `https://${process.env.AWS_S3_BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com/${key}`;
    
    // Cleanup local file generated by multer
    fs.unlinkSync(file.path);
  } else {
    // Local storage
    file_url = `/${process.env.UPLOADS_DIR || 'uploads/content'}/${file.filename}`;
  }

  return { file_url, file_type, file_size };
};
